package eu.isas.reporter.gui;

import com.compomics.util.examples.BareBonesBrowserLaunch;
import com.compomics.util.experiment.identification.SearchParameters;
import eu.isas.peptideshaker.scoring.MatchValidationLevel;
import eu.isas.reporter.myparameters.ReporterPreferences;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.JOptionPane;

/**
 * The preferences dialog.
 * 
 * @author Marc Vaudel
 * @author Harald Barsnes
 */
public class PreferencesDialog extends javax.swing.JDialog {

    /**
     * The Reporter GUI parent.
     */
    private ReporterGUI reporterGui;
    /**
     * The quantification preferences.
     */
    private ReporterPreferences quantificationPreferences;
    /**
     * The identification parameters
     */
    private SearchParameters searchParameters;
    /**
     * Modification file.
     */
    private final String MODIFICATIONS_FILE = "resources/conf/reporter_mods.xml";
    /**
     * User modification file.
     */
    private final String USER_MODIFICATIONS_FILE = "resources/conf/reporter_usermods.xml";

    /**
     * Creates a new PreferencesDialog.
     * 
     * @param reporterGui reference to the ReporterGUI
     * @param quantificationPreferences the quantification preferences
     * @param searchParameters the identification parameters
     */
    public PreferencesDialog(ReporterGUI reporterGui, ReporterPreferences quantificationPreferences, SearchParameters searchParameters) {
        super(reporterGui, true);
        this.reporterGui = reporterGui;
        this.quantificationPreferences = quantificationPreferences;
        this.searchParameters = searchParameters;
        initComponents();
        loadValues();
        updateModificationList();
        setLocationRelativeTo(reporterGui);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundPanel = new javax.swing.JPanel();
        idSelectionPanel = new javax.swing.JPanel();
        miscleavageCheck = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        selectedPtmsScrollPane = new javax.swing.JScrollPane();
        selectedPTMs = new javax.swing.JList();
        allPtmsScrollPane = new javax.swing.JScrollPane();
        allPTMs = new javax.swing.JList();
        jLabel8 = new javax.swing.JLabel();
        addModifications = new javax.swing.JButton();
        removeModification = new javax.swing.JButton();
        ratioEstimationsPanel = new javax.swing.JPanel();
        nullIntensitiesCheck = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        widthTxt = new javax.swing.JTextField();
        resolutionTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        peptideValidationCmb = new javax.swing.JComboBox();
        proteinValidationCmb = new javax.swing.JComboBox();
        psmValidationCmb = new javax.swing.JComboBox();
        cancelButton = new javax.swing.JButton();
        helpLabel = new javax.swing.JLabel();
        helpLinkLabel = new javax.swing.JLabel();
        okButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Quantification Preferences");

        backgroundPanel.setBackground(new java.awt.Color(230, 230, 230));

        idSelectionPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Identifications Selection"));
        idSelectionPanel.setOpaque(false);

        miscleavageCheck.setText("Ignore miscleaved peptides");
        miscleavageCheck.setIconTextGap(10);
        miscleavageCheck.setOpaque(false);

        jLabel1.setFont(jLabel1.getFont().deriveFont((jLabel1.getFont().getStyle() | java.awt.Font.ITALIC)));
        jLabel1.setText("Ignore peptides presenting the following PTMs");

        selectedPtmsScrollPane.setViewportView(selectedPTMs);

        allPTMs.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        allPtmsScrollPane.setViewportView(allPTMs);

        jLabel8.setFont(jLabel8.getFont().deriveFont((jLabel8.getFont().getStyle() | java.awt.Font.ITALIC)));
        jLabel8.setText("Available PTMs");

        addModifications.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/arrowUp_grey.png"))); // NOI18N
        addModifications.setText("Add");
        addModifications.setToolTipText("Add to list of expected modifications");
        addModifications.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        addModifications.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/arrowUp.png"))); // NOI18N
        addModifications.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addModificationsActionPerformed(evt);
            }
        });

        removeModification.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/arrowDown_grey.png"))); // NOI18N
        removeModification.setText("Remove");
        removeModification.setToolTipText("Remove from list of selected modifications");
        removeModification.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        removeModification.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/arrowDown.png"))); // NOI18N
        removeModification.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeModificationActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout idSelectionPanelLayout = new javax.swing.GroupLayout(idSelectionPanel);
        idSelectionPanel.setLayout(idSelectionPanelLayout);
        idSelectionPanelLayout.setHorizontalGroup(
            idSelectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(idSelectionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(idSelectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(idSelectionPanelLayout.createSequentialGroup()
                        .addGroup(idSelectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, idSelectionPanelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(addModifications, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(removeModification, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(allPtmsScrollPane)
                            .addComponent(selectedPtmsScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 524, Short.MAX_VALUE)
                            .addComponent(jLabel1))
                        .addContainerGap())
                    .addGroup(idSelectionPanelLayout.createSequentialGroup()
                        .addGroup(idSelectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(miscleavageCheck))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        idSelectionPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {addModifications, removeModification});

        idSelectionPanelLayout.setVerticalGroup(
            idSelectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(idSelectionPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(miscleavageCheck)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(selectedPtmsScrollPane)
                .addGroup(idSelectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(idSelectionPanelLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel8))
                    .addGroup(idSelectionPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(idSelectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(removeModification, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addModifications, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(allPtmsScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                .addContainerGap())
        );

        ratioEstimationsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Ratio Estimation"));
        ratioEstimationsPanel.setOpaque(false);

        nullIntensitiesCheck.setText("Ignore null intensities");
        nullIntensitiesCheck.setIconTextGap(10);
        nullIntensitiesCheck.setOpaque(false);

        jLabel4.setText("Resolution");

        jLabel5.setText("Window Width");

        jLabel6.setText("%");

        widthTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        resolutionTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel2.setText("Proteins");

        jLabel3.setText("Peptides");

        jLabel7.setText("PSMs");

        peptideValidationCmb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Confident Only", "Validated Only", "All" }));

        proteinValidationCmb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Confident Only", "Validated Only", "All" }));

        psmValidationCmb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Confident Only", "Validated Only", "All" }));

        javax.swing.GroupLayout ratioEstimationsPanelLayout = new javax.swing.GroupLayout(ratioEstimationsPanel);
        ratioEstimationsPanel.setLayout(ratioEstimationsPanelLayout);
        ratioEstimationsPanelLayout.setHorizontalGroup(
            ratioEstimationsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ratioEstimationsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ratioEstimationsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ratioEstimationsPanelLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(proteinValidationCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ratioEstimationsPanelLayout.createSequentialGroup()
                        .addGroup(ratioEstimationsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(ratioEstimationsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(psmValidationCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(peptideValidationCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(ratioEstimationsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nullIntensitiesCheck)
                    .addGroup(ratioEstimationsPanelLayout.createSequentialGroup()
                        .addGroup(ratioEstimationsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(ratioEstimationsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(widthTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                            .addComponent(resolutionTxt))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)))
                .addGap(6, 6, 6))
        );

        ratioEstimationsPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {peptideValidationCmb, psmValidationCmb});

        ratioEstimationsPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel2, jLabel3, jLabel7});

        ratioEstimationsPanelLayout.setVerticalGroup(
            ratioEstimationsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ratioEstimationsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ratioEstimationsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resolutionTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(proteinValidationCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ratioEstimationsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(widthTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3)
                    .addComponent(peptideValidationCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ratioEstimationsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nullIntensitiesCheck)
                    .addComponent(jLabel7)
                    .addComponent(psmValidationCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        helpLabel.setFont(helpLabel.getFont().deriveFont((helpLabel.getFont().getStyle() | java.awt.Font.ITALIC)));
        helpLabel.setText("For ratio estimation help see:");

        helpLinkLabel.setText("<html> <a href=\\\"dummy_link\">Burkhart et al.  (2011) [PMID: 21328540]</a>.</html>");
        helpLinkLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                helpLinkLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                helpLinkLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                helpLinkLabelMouseExited(evt);
            }
        });

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout backgroundPanelLayout = new javax.swing.GroupLayout(backgroundPanel);
        backgroundPanel.setLayout(backgroundPanelLayout);
        backgroundPanelLayout.setHorizontalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(helpLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(helpLinkLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                        .addComponent(okButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelButton))
                    .addComponent(idSelectionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ratioEstimationsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        backgroundPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cancelButton, okButton});

        backgroundPanelLayout.setVerticalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(idSelectionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ratioEstimationsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(helpLabel)
                    .addComponent(helpLinkLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelButton)
                    .addComponent(okButton))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Close the dialog.
     * 
     * @param evt 
     */
    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    /**
     * Changes the cursor to the hand cursor when over the help link.
     *
     * @param evt
     */
    private void helpLinkLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_helpLinkLabelMouseEntered
        this.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_helpLinkLabelMouseEntered

    /**
     * Changes the cursor back to the default cursor when leaving the help link.
     *
     * @param evt
     */
    private void helpLinkLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_helpLinkLabelMouseExited
        this.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_helpLinkLabelMouseExited

    /**
     * Opens the help link in the web browser.
     *
     * @param evt
     */
    private void helpLinkLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_helpLinkLabelMouseClicked
        this.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        BareBonesBrowserLaunch.openURL("http://onlinelibrary.wiley.com/doi/10.1002/pmic.201000711/abstract");
        this.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_helpLinkLabelMouseClicked

    /**
     * Add a modification to the list.
     * 
     * @param evt 
     */
    private void addModificationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addModificationsActionPerformed

        int nSelected = selectedPTMs.getModel().getSize();
        int nNew = allPTMs.getSelectedIndices().length;
        String[] fixedModifications = new String[nSelected + nNew];
        int cpt = 0;

        for (int i = 0; i < nSelected; i++) {
            fixedModifications[cpt] = (String) selectedPTMs.getModel().getElementAt(i);
            cpt++;
        }
        boolean found;
        for (Object selection : allPTMs.getSelectedValuesList()) {
            String name = (String) selection;
            found = false;
            for (int i = 0; i < selectedPTMs.getModel().getSize(); i++) {
                if (((String) selectedPTMs.getModel().getElementAt(i)).equals(name)) {
                    found = true;
                    break;
                }
            }
            if (!found) {
                fixedModifications[cpt] = name;
                cpt++;
            }
        }
        selectedPTMs.setListData(fixedModifications);
        updateModificationList();
    }//GEN-LAST:event_addModificationsActionPerformed

    /**
     * Remove a modification from the list.
     * 
     * @param evt 
     */
    private void removeModificationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeModificationActionPerformed

        int nSelected = selectedPTMs.getModel().getSize();
        int nToRemove = selectedPTMs.getSelectedIndices().length;
        String[] variableModifications = new String[nSelected - nToRemove];
        int cpt = 0;
        boolean found;
        for (int i = 0; i < selectedPTMs.getModel().getSize(); i++) {
            found = false;
            for (Object selection : selectedPTMs.getSelectedValuesList()) {
                if (((String) selectedPTMs.getModel().getElementAt(i)).equals((String) selection)) {
                    found = true;
                    break;
                }
            }
            if (!found) {
                variableModifications[cpt] = (String) selectedPTMs.getModel().getElementAt(i);
                cpt++;
            }
        }
        selectedPTMs.setListData(variableModifications);
        updateModificationList();
    }//GEN-LAST:event_removeModificationActionPerformed

    /**
     * Save the data and close the dialog.
     * 
     * @param evt 
     */
    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        if (validateInput()) {
            saveValues();
            dispose();
        }
    }//GEN-LAST:event_okButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addModifications;
    private javax.swing.JList allPTMs;
    private javax.swing.JScrollPane allPtmsScrollPane;
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel helpLabel;
    private javax.swing.JLabel helpLinkLabel;
    private javax.swing.JPanel idSelectionPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JCheckBox miscleavageCheck;
    private javax.swing.JCheckBox nullIntensitiesCheck;
    private javax.swing.JButton okButton;
    private javax.swing.JComboBox peptideValidationCmb;
    private javax.swing.JComboBox proteinValidationCmb;
    private javax.swing.JComboBox psmValidationCmb;
    private javax.swing.JPanel ratioEstimationsPanel;
    private javax.swing.JButton removeModification;
    private javax.swing.JTextField resolutionTxt;
    private javax.swing.JList selectedPTMs;
    private javax.swing.JScrollPane selectedPtmsScrollPane;
    private javax.swing.JTextField widthTxt;
    // End of variables declaration//GEN-END:variables

    /**
     * Loads values from the quantificationPreferences.
     */
    private void loadValues() {
        miscleavageCheck.setSelected(quantificationPreferences.isIgnoreMissedCleavages());
        nullIntensitiesCheck.setSelected(quantificationPreferences.isIgnoreNullIntensities());
        widthTxt.setText(quantificationPreferences.getPercentile()+ "");
        resolutionTxt.setText(quantificationPreferences.getRatioResolution() + "");
        ArrayList<String> selectedModificationsList = quantificationPreferences.getexcludingPtms();
        String[] allModificationsAsArray = new String[selectedModificationsList.size()];
        for (int i = 0; i < selectedModificationsList.size(); i++) {
            allModificationsAsArray[i] = selectedModificationsList.get(i);
        }
        selectedPTMs.setListData(allModificationsAsArray);
        updateModificationList();
        proteinValidationCmb.setSelectedIndex(2-quantificationPreferences.getProteinValidationLevel().getIndex());
        peptideValidationCmb.setSelectedIndex(2-quantificationPreferences.getPeptideValidationLevel().getIndex());
        psmValidationCmb.setSelectedIndex(2-quantificationPreferences.getPsmValidationLevel().getIndex());
    }

    /**
     * Saves the values in the quantificationPreferences.
     */
    private void saveValues() {
        quantificationPreferences.setIgnoreMissedCleavages(miscleavageCheck.isSelected());
        quantificationPreferences.setIgnoreNullIntensities(nullIntensitiesCheck.isSelected());
        quantificationPreferences.setPercentile(new Double(widthTxt.getText()));
        quantificationPreferences.setRatioResolution(new Double(resolutionTxt.getText()));
        quantificationPreferences.emptyPTMList();
        String name;
        for (int j = 0; j < selectedPTMs.getModel().getSize(); j++) {
            name = (String) selectedPTMs.getModel().getElementAt(j);
            quantificationPreferences.addExcludingPtm(name);
        }
        quantificationPreferences.setProteinValidationLevel(MatchValidationLevel.getMatchValidationLevel(2-proteinValidationCmb.getSelectedIndex()));
        quantificationPreferences.setPeptideValidationLevel(MatchValidationLevel.getMatchValidationLevel(2-peptideValidationCmb.getSelectedIndex()));
        quantificationPreferences.setPsmValidationLevel(MatchValidationLevel.getMatchValidationLevel(2-psmValidationCmb.getSelectedIndex()));
    }

    /**
     * Methods which validates the user input (returns false in case of wrong
     * input).
     *
     * @return true if the input can be processed
     */
    private boolean validateInput() {
        try {
            new Double(widthTxt.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "please enter a correct window width.", "Window width error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        try {
            new Double(resolutionTxt.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "please enter a correct ratio resolution.", "Ratio resolution error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;
    }

    /**
     * Updates the modification list (right).
     */
    private void updateModificationList() {
        ArrayList<String> allModificationsList = new ArrayList<String>(searchParameters.getModificationProfile().getAllNotFixedModifications());
        int nSelected = selectedPTMs.getModel().getSize();
        ArrayList<String> allModifications = new ArrayList<String>();

        for (String name : allModificationsList) {
            boolean found = false;
            for (int j = 0; j < nSelected; j++) {
                if (((String) selectedPTMs.getModel().getElementAt(j)).equals(name)) {
                    found = true;
                    break;
                }
            }
            if (!found) {
                allModifications.add(name);
            }
        }

        String[] allModificationsAsArray = new String[allModifications.size()];

        for (int i = 0; i < allModifications.size(); i++) {
            allModificationsAsArray[i] = allModifications.get(i);
        }

        Arrays.sort(allModificationsAsArray);
        allPTMs.setListData(allModificationsAsArray);
        allPTMs.setSelectedIndex(0);
    }
}
